name: Cron Jobs

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Manual trigger button

jobs:
  run-crons:
    runs-on: ubuntu-latest
    steps:
      - name: Making Order Payment
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://kawsa-clinic-ecommerce.vercel.app/api/easyparcel/making-order-payment

      - name: Sync AWB
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://kawsa-clinic-ecommerce.vercel.app/api/easyparcel/sync-awb

      - name: Email Send Tracking
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://kawsa-clinic-ecommerce.vercel.app/api/email-send-tracking
